/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationRetriesRouteImport } from './routes/integration.retries'
import { Route as IntegrationLogsRouteImport } from './routes/integration.logs'
import { Route as IntegrationCredentialsRouteImport } from './routes/integration.credentials'
import { Route as ChannelsChannelIdRouteImport } from './routes/channels.$channelId'
import { Route as AiTrainingRouteImport } from './routes/ai.training'
import { Route as AiSourcesRouteImport } from './routes/ai.sources'
import { Route as AiQualityRouteImport } from './routes/ai.quality'
import { Route as AiPlaygroundRouteImport } from './routes/ai.playground'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRetriesRoute = IntegrationRetriesRouteImport.update({
  id: '/retries',
  path: '/retries',
  getParentRoute: () => IntegrationRoute,
} as any)
const IntegrationLogsRoute = IntegrationLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => IntegrationRoute,
} as any)
const IntegrationCredentialsRoute = IntegrationCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => IntegrationRoute,
} as any)
const ChannelsChannelIdRoute = ChannelsChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => ChannelsRoute,
} as any)
const AiTrainingRoute = AiTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AiRoute,
} as any)
const AiSourcesRoute = AiSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AiRoute,
} as any)
const AiQualityRoute = AiQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AiRoute,
} as any)
const AiPlaygroundRoute = AiPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/audit': typeof AuditRoute
  '/backup': typeof BackupRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/complaints': typeof ComplaintsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/integration': typeof IntegrationRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/users': typeof UsersRoute
  '/workflows': typeof WorkflowsRoute
  '/ai/playground': typeof AiPlaygroundRoute
  '/ai/quality': typeof AiQualityRoute
  '/ai/sources': typeof AiSourcesRoute
  '/ai/training': typeof AiTrainingRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/integration/credentials': typeof IntegrationCredentialsRoute
  '/integration/logs': typeof IntegrationLogsRoute
  '/integration/retries': typeof IntegrationRetriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/audit': typeof AuditRoute
  '/backup': typeof BackupRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/complaints': typeof ComplaintsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/integration': typeof IntegrationRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/users': typeof UsersRoute
  '/workflows': typeof WorkflowsRoute
  '/ai/playground': typeof AiPlaygroundRoute
  '/ai/quality': typeof AiQualityRoute
  '/ai/sources': typeof AiSourcesRoute
  '/ai/training': typeof AiTrainingRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/integration/credentials': typeof IntegrationCredentialsRoute
  '/integration/logs': typeof IntegrationLogsRoute
  '/integration/retries': typeof IntegrationRetriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/audit': typeof AuditRoute
  '/backup': typeof BackupRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/complaints': typeof ComplaintsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/integration': typeof IntegrationRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/users': typeof UsersRoute
  '/workflows': typeof WorkflowsRoute
  '/ai/playground': typeof AiPlaygroundRoute
  '/ai/quality': typeof AiQualityRoute
  '/ai/sources': typeof AiSourcesRoute
  '/ai/training': typeof AiTrainingRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/integration/credentials': typeof IntegrationCredentialsRoute
  '/integration/logs': typeof IntegrationLogsRoute
  '/integration/retries': typeof IntegrationRetriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/audit'
    | '/backup'
    | '/channels'
    | '/complaints'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/integration'
    | '/knowledge'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/survey'
    | '/users'
    | '/workflows'
    | '/ai/playground'
    | '/ai/quality'
    | '/ai/sources'
    | '/ai/training'
    | '/channels/$channelId'
    | '/integration/credentials'
    | '/integration/logs'
    | '/integration/retries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/audit'
    | '/backup'
    | '/channels'
    | '/complaints'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/integration'
    | '/knowledge'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/survey'
    | '/users'
    | '/workflows'
    | '/ai/playground'
    | '/ai/quality'
    | '/ai/sources'
    | '/ai/training'
    | '/channels/$channelId'
    | '/integration/credentials'
    | '/integration/logs'
    | '/integration/retries'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/audit'
    | '/backup'
    | '/channels'
    | '/complaints'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/integration'
    | '/knowledge'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/survey'
    | '/users'
    | '/workflows'
    | '/ai/playground'
    | '/ai/quality'
    | '/ai/sources'
    | '/ai/training'
    | '/channels/$channelId'
    | '/integration/credentials'
    | '/integration/logs'
    | '/integration/retries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRouteWithChildren
  AuditRoute: typeof AuditRoute
  BackupRoute: typeof BackupRoute
  ChannelsRoute: typeof ChannelsRouteWithChildren
  ComplaintsRoute: typeof ComplaintsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  InboxRoute: typeof InboxRoute
  IntegrationRoute: typeof IntegrationRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PermissionsRoute: typeof PermissionsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SurveyRoute: typeof SurveyRoute
  UsersRoute: typeof UsersRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/retries': {
      id: '/integration/retries'
      path: '/retries'
      fullPath: '/integration/retries'
      preLoaderRoute: typeof IntegrationRetriesRouteImport
      parentRoute: typeof IntegrationRoute
    }
    '/integration/logs': {
      id: '/integration/logs'
      path: '/logs'
      fullPath: '/integration/logs'
      preLoaderRoute: typeof IntegrationLogsRouteImport
      parentRoute: typeof IntegrationRoute
    }
    '/integration/credentials': {
      id: '/integration/credentials'
      path: '/credentials'
      fullPath: '/integration/credentials'
      preLoaderRoute: typeof IntegrationCredentialsRouteImport
      parentRoute: typeof IntegrationRoute
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/ai/training': {
      id: '/ai/training'
      path: '/training'
      fullPath: '/ai/training'
      preLoaderRoute: typeof AiTrainingRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/sources': {
      id: '/ai/sources'
      path: '/sources'
      fullPath: '/ai/sources'
      preLoaderRoute: typeof AiSourcesRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/quality': {
      id: '/ai/quality'
      path: '/quality'
      fullPath: '/ai/quality'
      preLoaderRoute: typeof AiQualityRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/playground': {
      id: '/ai/playground'
      path: '/playground'
      fullPath: '/ai/playground'
      preLoaderRoute: typeof AiPlaygroundRouteImport
      parentRoute: typeof AiRoute
    }
  }
}

interface AiRouteChildren {
  AiPlaygroundRoute: typeof AiPlaygroundRoute
  AiQualityRoute: typeof AiQualityRoute
  AiSourcesRoute: typeof AiSourcesRoute
  AiTrainingRoute: typeof AiTrainingRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiPlaygroundRoute: AiPlaygroundRoute,
  AiQualityRoute: AiQualityRoute,
  AiSourcesRoute: AiSourcesRoute,
  AiTrainingRoute: AiTrainingRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface ChannelsRouteChildren {
  ChannelsChannelIdRoute: typeof ChannelsChannelIdRoute
}

const ChannelsRouteChildren: ChannelsRouteChildren = {
  ChannelsChannelIdRoute: ChannelsChannelIdRoute,
}

const ChannelsRouteWithChildren = ChannelsRoute._addFileChildren(
  ChannelsRouteChildren,
)

interface IntegrationRouteChildren {
  IntegrationCredentialsRoute: typeof IntegrationCredentialsRoute
  IntegrationLogsRoute: typeof IntegrationLogsRoute
  IntegrationRetriesRoute: typeof IntegrationRetriesRoute
}

const IntegrationRouteChildren: IntegrationRouteChildren = {
  IntegrationCredentialsRoute: IntegrationCredentialsRoute,
  IntegrationLogsRoute: IntegrationLogsRoute,
  IntegrationRetriesRoute: IntegrationRetriesRoute,
}

const IntegrationRouteWithChildren = IntegrationRoute._addFileChildren(
  IntegrationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRouteWithChildren,
  AuditRoute: AuditRoute,
  BackupRoute: BackupRoute,
  ChannelsRoute: ChannelsRouteWithChildren,
  ComplaintsRoute: ComplaintsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  InboxRoute: InboxRoute,
  IntegrationRoute: IntegrationRouteWithChildren,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PermissionsRoute: PermissionsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SurveyRoute: SurveyRoute,
  UsersRoute: UsersRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
